CREATE TABLE sm16_answers(
AnswerID INT UNSIGNED NOT NULL AUTO_INCREMENT,
SurveyID INT UNSIGNED DEFAULT 0,
QuestionID INT UNSIGNED DEFAULT 0,
Answer TEXT DEFAULT '',
DateAdded TIMESTAMP DEFAULT 0,
PRIMARY KEY (AnswerID),
FOREIGN KEY (SurveyID) REFERENCES sm16_surveys(SurveyID),
FOREIGN KEY (QuestionID) REFERENCES sm16_questions(QuestionID) 
);